### ISSUE TITLE
Consistent elm import

### ISSUE THREAD

**Issue by andys8** [evancz/components#6]
The angular example is using destructuring, while the vue and react example are not. This should be independant from `require` vs `import` syntax, but I think it might be depending on the elm version used. I think it might be a mistake.

https://github.com/evancz/components/blob/dcc2d50aa529f51d63a6842a69ea8417296e9d16/vue.js#L1
https://github.com/evancz/components/blob/dcc2d50aa529f51d63a6842a69ea8417296e9d16/react.js#L1
https://github.com/evancz/components/blob/dcc2d50aa529f51d63a6842a69ea8417296e9d16/angular.ts#L2

**Comment by brian-carroll** [comment]
The Angular example is also written in a different language though! 😀
All of these examples are consistent with their respective frameworks. `require` is not normally used in Angular.

For someone integrating into an existing project, i think they need consistency *within that project*. I presume they wouldn't be so interested in consistency with examples from other frameworks.

At least that's how I see it. It's Evan's call whether I'm misinterpreting the goals of this repo. Happy to submit another PR if he asks for it.

**Comment by andys8** [comment]
There is the difference between `require` and `import`. That's fine. But named default (`import Elm ..`)  vs. destructuring (`import { Elm } ..`) will actually do something different, right? Am I missing something with [Typescript module resolution](https://www.typescriptlang.org/docs/handbook/module-resolution.html)?

If all the elm examples are working fine, with the newest version everything might be fine, though :)

**Comment by brian-carroll** [comment]
I should also add that the first thing I tried was
```
import * from '../distribution/elm/main';
Elm.Main.init( /* whatever */)
```
That's what I expected to work, and it would be in line with what you expected too. But it didn't work. I'm not sure why, to be honest. I didn't look hard at how the generated code exports stuff. Just played with it till it ran without throwing exceptions, and displayed the Elm view in the Angular view.

**Comment by brian-carroll** [comment]
Oh and I used Elm 0.19 by the way. I could publish my test case tomorrow if you want to verify.

**Comment by andys8** [comment]
I'm also using 0.19 and I have something in mind, that I read somebody noticing a change, but I can't find it.

I made some tests using Webpack. The results are the same you had with ts and elm 0.19. So it could be that the ts example is the only one being up-to-date, and the others aren't ;)

## Works
```js
import { Elm } from './elmdist.js'; 
Elm.Main.init({node: document.getElementById('elm-embed')});
```
Also
```js
var { Elm } = require('./elmdist.js');
```

## Doesn't work
```js
import Elm from './elmdist.js'; 
var Elm = require('./elmdist.js');
```

**Comment by evancz** [comment]
I think it's important to be consistent within the example and try for code that does not need special compilation. If there is some bug, talk about it in a separate issue.

**Comment by andys8** [comment]
@evancz Can you clarify how elm has to be imported and if there is difference depending on the elm compiler version?
